with
source as (
    SELECT * EXCEPT (category, app),

    CASE WHEN category IS NULL THEN "N/A"
    ELSE category 
    END as Cat_app,

    CASE 
        WHEN LOWER(app) LIKE '%google.android%' AND LOWER(app) NOT LIKE '%youtube%' THEN 'android'
        WHEN LOWER(app) LIKE '%youtube%' THEN 'youtube'
        WHEN LOWER(app) LIKE '%instagram%' THEN 'instagram'
        WHEN LOWER(app) LIKE '%qualcomm%' THEN 'qualcomm'
        WHEN LOWER(app) LIKE 'android' THEN 'android'
        WHEN LOWER(app) LIKE 'com.android%' THEN 'android'
        WHEN LOWER(app) LIKE 'com.sec.android%' THEN 'android'
        WHEN LOWER(app) LIKE 'com.samsung.android%' THEN 'android'
        WHEN LOWER(app) LIKE '%twitter%' THEN 'twitter'
        WHEN LOWER(app) LIKE '%whatsapp%' THEN 'whatsapp'
        WHEN LOWER(app) LIKE '%mixplorer%' THEN 'mixplorer'
        WHEN LOWER(app) LIKE '%spotify%' THEN 'spotify'
        WHEN LOWER(app) LIKE '%vodafone%' THEN 'vodafone'
        WHEN LOWER(app) LIKE '%telegram%' THEN 'telegram'
        WHEN LOWER(app) LIKE '%sensapp%' THEN 'sensapp'
        WHEN LOWER(app) LIKE '%rsoft%' THEN 'rsoft'
        WHEN LOWER(app) LIKE '%argosoft%' THEN 'argosoft'
        WHEN LOWER(app) LIKE '%minecraftpe%' THEN 'minecraftpe'
        WHEN LOWER(app) LIKE '%robtopx%' THEN 'robtopx'
        WHEN LOWER(app) LIKE '%supercell%' THEN 'supercell'
        WHEN LOWER(app) LIKE '%studio8apps%' THEN 'studio8apps'
        WHEN LOWER(app) LIKE '%samsung%' AND LOWER(app) NOT LIKE '%samsung.android%' THEN 'samsung'
        WHEN LOWER(app) LIKE '%facebook%' THEN 'facebook'
        WHEN LOWER(app) LIKE '%.sec.%' THEN 'sec'
        WHEN LOWER(app) LIKE '%skype%' THEN 'skype'
    WHEN LOWER(app) LIKE '%bluemail%' THEN 'bluemail'
    WHEN LOWER(app) LIKE '%videolan%' THEN 'videolan'
    WHEN LOWER(app) LIKE '%motorola%' THEN 'motorola'
    WHEN LOWER(app) LIKE '%dropbox%' THEN 'dropbox'
    WHEN LOWER(app) LIKE '%soundcloud%' THEN 'soundcloud'
    WHEN LOWER(app) LIKE '%ryanair%' THEN 'ryanair'
    WHEN LOWER(app) LIKE '%tripadvisor%' THEN 'tripadvisor'
    WHEN LOWER(app) LIKE '%booking%' THEN 'booking'
    WHEN LOWER(app) LIKE '%ubercab%' THEN 'ubercab'
    WHEN LOWER(app) LIKE '%duolingo%' THEN 'duolingo'
    WHEN LOWER(app) LIKE '%roomster%' THEN 'roomster'
    WHEN LOWER(app) LIKE '%miui%' THEN 'miui'
    WHEN LOWER(app) LIKE '%wikipedia%' THEN 'wikipedia'
    WHEN LOWER(app) LIKE '%badoo%' THEN 'badoo'
    WHEN LOWER(app) LIKE '%airbnb%' THEN 'airbnb'
    WHEN LOWER(app) LIKE '%xiaomi%' THEN 'xiaomi'
    WHEN LOWER(app) LIKE '%hostelworld%' THEN 'hostelworld'
    WHEN LOWER(app) LIKE '%linkedin%' THEN 'linkedin'
    WHEN LOWER(app) LIKE '%roomiapp%' THEN 'roomiapp'
    WHEN LOWER(app) LIKE '%tratao%' THEN 'tratao'
    WHEN LOWER(app) LIKE '%roommate%' THEN 'roommate'
    WHEN LOWER(app) LIKE '%alibaba%' THEN 'alibaba'
    WHEN LOWER(app) LIKE '%skyscanner%' THEN 'skyscanner'
    WHEN LOWER(app) LIKE '%amazon%' THEN 'amazon'
    WHEN LOWER(app) LIKE '%.mi.%' THEN 'mi'
    WHEN LOWER(app) LIKE '%yahoo%' THEN 'yahoo'
    WHEN LOWER(app) LIKE '%playstation%' THEN 'playstation'
    WHEN LOWER(app) LIKE '%trivago%' THEN 'trivago'
    WHEN LOWER(app) LIKE '%huawei%' THEN 'huawei'
    WHEN LOWER(app) LIKE '%netflix%' THEN 'netflix'
    WHEN LOWER(app) LIKE '%tumblr%' THEN 'tumblr'
    WHEN LOWER(app) LIKE '%shazam%' THEN 'shazam'
    WHEN LOWER(app) LIKE '%snapchat%' THEN 'snapchat'
    WHEN LOWER(app) LIKE '%ketchapp%' THEN 'ketchapp'
    WHEN LOWER(app) LIKE '%letterboxd%' THEN 'letterboxd'
    WHEN LOWER(app) LIKE '%translator%' THEN 'translator'
    WHEN LOWER(app) LIKE '%photoeditor%' THEN 'photoeditor'
    WHEN LOWER(app) LIKE '%asus%' THEN 'asus'
    WHEN LOWER(app) LIKE '%wordreference%' THEN 'wordreference'
    WHEN LOWER(app) LIKE '%microsoft%' THEN 'microsoft'
    WHEN LOWER(app) LIKE '%telecomitalia%' THEN 'telecomitalia'
    WHEN LOWER(app) LIKE '%gopro%' THEN 'gopro'
    WHEN LOWER(app) LIKE '%.ea.%' THEN 'ea'
    WHEN LOWER(app) LIKE '%gmail%' THEN 'gmail'
    WHEN LOWER(app) LIKE '%adobe%' THEN 'adobe'
    WHEN LOWER(app) LIKE '%antivirus%' THEN 'antivirus'
    WHEN LOWER(app) LIKE '%oneplus%' THEN 'oneplus'
    WHEN LOWER(app) LIKE '%handyapps%' THEN 'handyapps'
    WHEN LOWER(app) LIKE '%ebay%' THEN 'ebay'
    WHEN LOWER(app) LIKE '%justeat%' THEN 'justeat'
    WHEN LOWER(app) LIKE '%pinterest%' THEN 'pinterest'
    WHEN LOWER(app) LIKE '%wordgame%' THEN 'wordgame'
    WHEN LOWER(app) LIKE '%isitlove%' THEN 'isitlove'
    WHEN LOWER(app) LIKE '%voodoo%' THEN 'voodoo'
    WHEN LOWER(app) LIKE '%fungames%' THEN 'fungames'
    WHEN LOWER(app) LIKE '%mcdonalds%' THEN 'mcdonalds'
    WHEN LOWER(app) LIKE '%gamefox%' THEN 'gamefox'
    WHEN LOWER(app) LIKE '%twitch%' THEN 'twitch'
    WHEN LOWER(app) LIKE '%panasonic%' THEN 'panasonic'
    WHEN LOWER(app) LIKE '%.lge.%' THEN 'lge'
    WHEN LOWER(app) LIKE '%nikon%' THEN 'nikon'
    WHEN LOWER(app) LIKE '%.hp.%' THEN 'hp'
    WHEN LOWER(app) LIKE '%nikon%' THEN 'nikon'
    WHEN LOWER(app) LIKE '%sandbox%' THEN 'sandbox'
    WHEN LOWER(app) LIKE '%google.earth%' THEN 'google.earth'
    WHEN LOWER(app) LIKE '%mozilla%' THEN 'mozilla'
        -- REVISAR CUANDO SEA APPLE--
   ELSE 'other' 
   END AS app_running_source

   FROM {{ source('IDA_MDF_raw', 'running_apps') }}
)

SELECT *
FROM source
